drop table cic;
drop table entity;
create table cic (
  body varchar(255),
  cic_id bigint,
  cic_timestamp date,
  cic_type varchar(255),
  source_system varchar(255),
  subject varchar(255),
  entity_id bigint not null,
  primary key (entity_id)
);
create table entity (
  entity_id bigint generated by default as identity,
  email_address varchar(255),
  entity_name varchar(255),
  primary key (entity_id)
);
alter table cic
  add constraint FK_ENTITY_CIC
foreign key (entity_id)
references entity
